apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: mosesr/vote-app3
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: postgres