apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: mosesr/vote-app2
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis